name: Atualizar Exams baseado nas notas dos alunos por módulo

on:
  schedule:
    - cron: "00 15 * * *"  # Roda todos os dias às 12:00 Br
  workflow_dispatch:
  
jobs:
  atualizar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar este repositório de automação
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt

      - name: Exportar variáveis para os scripts
        run: |
          echo "PL_TOKEN=${{ secrets.PL_TOKEN }}" >> $GITHUB_ENV
          echo "DEFAULT_CURSO=${{ secrets.DEFAULT_CURSO }}" >> $GITHUB_ENV
          echo "COURSE_INSTANCE_ID=${{ secrets.DEFAULT_COURSE_INSTANCE_ID }}" >> $GITHUB_ENV

      - name: Baixar gradebook e gerar aprovados por módulo
        run: |
          python3 baixar_e_filtrar_modulos.py -i ${{ secrets.DEFAULT_COURSE_INSTANCE_ID }}

      - name: Clonar repositório do curso
        run: |
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/PrairieLearn/pl-insper-nccc101.git curso

      - name: Atualizar arquivos infoAssessment dos Exams
        run: |
          python3 pl_gradebook/atualizar_allow_access.py

      - name: Copiar os arquivos gerados para o repositório do curso
        run: |
          for i in 1 2 3 4
          do
            cp pl_gradebook/exam${i}_atualizado.json curso/courseInstances/${{ secrets.DEFAULT_CURSO }}/assessments/Quiz${i}/infoAssessment.json
          done

      - name: Commit e push no repositório do curso
        run: |
          cd curso
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add courseInstances/${{ secrets.DEFAULT_CURSO }}/assessments/Quiz*/infoAssessment.json
          git commit -m "Atualização automática de infoAssessment via automacoes-pl" || echo "Sem mudanças"
          git push

